### ISSUE TITLE
Password-strength-o-meter contradiction

### ISSUE THREAD

**Issue by Peneheals** [howsecureismypassword/hsimp#19]
If I use the below passwords, it shows a contradiction:

`asdfghjklmnbvcxyasd` is green and looks good and strong (2 billion years), meanwhile `asdfghjklmnbvcxyasd4` is orange and looks worse (42 trillion years).

And there is another one:

There is a difference between the bower build and the webpage. With the above passwords:
asdfghjklmnbvcxyasd - 607 million vs 2 billion
asdfghjklmnbvcxyasd4 - 11 trillion vs 42 trillion

**Comment by smallhadroncollider** [comment]
The second one is orange as one of the checks is for a series of letters followed by a number - it's a very common password pattern, so it gives a warning. The time it would take to crack goes up because the check is fairly dumb, so it can't check if it *is* a word followed by a number.

As for the inconsistency between the webpage and the bower build: you can change the default number of calculation per second in the settings. I think I've updated the website more recently than the GitHub script (they don't use quite the same code).
