### ISSUE TITLE
Inaccurate time when using low ascii symbols

### ISSUE THREAD

**Issue by Okimoka** [howsecureismypassword/hsimp#3]
Ascii symbols like "start of header" or "start of text" (or String.fromCharCode(1) / String.fromCharCode(2)) do not add any calculation time.
You could input twenty STX characters and you would get "0 YOCTOSECONDS" as the result

**Comment by smallhadroncollider** [comment]
There's quite a lot of possible symbols that aren't included in the check.

If you want to add some groupings, feel free to do a pull request: https://github.com/howsecureismypassword/modules-character-sets/blob/develop/character-sets.json

**Comment by stephenreay** [comment]
Same is true for emoji, and eg Thai characters. I'll try to find some time to add more character classes.

Related: the emoji keyboard isn't available when the input box is focused in Safari on the reference site. Possibly the page/form is set to a charset other than UTF8?

**Comment by smallhadroncollider** [comment]
Sorry for the slow response. As far as I can tell iOS doesn't let you change keyboard layouts for `<input type="password" />`. I've added `UTF-8` to the form just in case, but it doesn't seem to make any difference.

**Comment by smallhadroncollider** [comment]
I've updated the core code so that if it detects a character that isn't in the set list of character sets it will assume it belongs to a set with 1000 characters in it. That's a fairly arbitrary number, but it does mean that all characters will now register.

Hopefully I might get some time in September to update the character sets to include a much larger set of Unicode than it currently does.
